### ISSUE TITLE
[Feature Request] Npm package

### ISSUE THREAD

**Issue by PedroAugustoRamalhoDuarte** [creativetimofficial/vision-ui-dashboard-chakra#1]
### What is your enhancement?
It would be interesting if it had an npm package with the components

**Comment by simmmpleweb** [comment]
Hi, @PedroAugustoRamalhoDuarte ! Thanks for using our products. That is a good idea, we will take your request into consideration. Until then, we hope our products are helpful for you !  Regards, Vlad.
