### ISSUE TITLE
Node-gyp Installation Error

### ISSUE THREAD

**Issue by Moltivie** [creativetimofficial/vision-ui-dashboard-chakra#3]
What's the problem with this?

![image](https://user-images.githubusercontent.com/14014692/166106839-3cd65dc5-38c2-45a8-993c-cfabc795cf1c.png)

**Comment by Moltivie** [comment]
@timcreative any suggestions?

**Comment by simmmpleweb** [comment]
Hello, @Moltivie ! Thanks for using our products ! Check if React is installed globally. If that doesn't work, the problem might be related to your npm/yarn version. Regards, Vlad.

**Comment by gerald-gt** [comment]
Yes I got the same issue, It's look like react version. What is correct version will solve this issue. 
Do you have version number ?

**Comment by simmmpleweb** [comment]
We removed deprecated deps/ plugins and now you should not get the error. If you still want to use the plugin version, try using npm --force install or npm --legacy-peer-deps install for now.
